### ISSUE TITLE
text with many < br/> 

### ISSUE THREAD

**Issue by TigerShark92** [Zimbelstern/Tournant#14]
Hi,
at first i want to thank you for your work an the app.
I have the issue that in every text it shows < br/>.
See this screenshot:
![Screenshot_2023-07-29-13-39-00-538-edit_eu zimbelstern tournant](https://github.com/Zimbelstern/Tournant/assets/140891998/ef60a3eb-f3bf-4d2d-aab8-3bd73369a9e5)
So i could not see the quantity of the ingredients.
I use version 2.2.1 of Tournant on a Redmi Note 10.
Gourmet is Version 0.17.4.
In older tournant versions it will work, but they have other issues.

**Comment by Zimbelstern** [comment]
Hi,
it seems like Gourmet 0.17.4 exports all tags with line breaks but I don't have this version at hand to confirm this. Could you please attach an exported .xml/.grmt file with an affected recipe so that I can have a look at it?

**Comment by TigerShark92** [comment]
Hi and thanks for your reply.
Yes, that seems to be the problem. Here is the example from the picture. I just renamed it from .xml to .txt to upload it.
[Rezepte Einzeln 0.17.4.txt](https://github.com/Zimbelstern/Tournant/files/12215753/Rezepte.Einzeln.0.17.4.txt)
I have tried an older version of Gourmet (0.15.4.) with a new recipe and it gave me the same XML with many line breaks.
Which version do you use? Maybe it is because I use Gourmet on Windows?

**Comment by Zimbelstern** [comment]
Version 0.17.4 was released in 2014 but there hasn't been any active development since then. When more and more Linux distributions abandoned Python 2 in favor of Python 3, someone forked the project and put a lot of work into patching up the code for Python 3. The project was renamed to [Gourmand](https://github.com/GourmandRecipeManager/gourmand) and the latest version is 1.1.0 now. I don't know if they have built a Windows version. Nevertheless, there are a lot of open bugs in Gourmand and it seems that nobody resumes working on the project. I personally am not happy with the situation because I prefer not to switch to Android completely but I haven't found an alternative for desktop that fulfills my requirements. If you are fine with your installed version of Gourmet, I would not recommend upgrading to Gourmand. I will provide a fix for the whitespace problem. And the next Tournant version will be released very soon.
