### ISSUE TITLE
Seemingly unable to import recipe 

### ISSUE THREAD

**Issue by serpico** [Zimbelstern/Tournant#19]
first tested with version 2.6.0 ( from F-Droid ) then with version 2.7.0 ( F-Droid ) - Android 6.0.1

I exported the recipe from Gourmand 1.0.0

I tried to import a newly created ( with Gourmand ) and exported recipe ( I just renamed the file from .grmt to .txt to be able to send it to github )
[Gateau de semoule 2024.txt](https://github.com/Zimbelstern/Tournant/files/15334350/Gateau.de.semoule.2024.txt)

then got this error message
![Screenshot_20240516-131621](https://github.com/Zimbelstern/Tournant/assets/1227077/a9b82b21-8f5e-4ece-9b2e-ca2ead82d237)

tried updating to 2.7.0, same message, same behavior

I tried importing an older recipe, ( the one you see in the screenshot "Riz au lait normand", I imported it a while ago using 2.5.0 or an older version ) and got the same message, I attach it as well in case you'd want to look at it

[Riz au lait normand.txt](https://github.com/Zimbelstern/Tournant/files/15334388/Riz.au.lait.normand.txt)

Finally renamed the file from Gateau.de.semoule.2024.grmt to Gateau.de.semoule.2024.xml and it worked

Thanks for your work creating and making the app available.

**Comment by Zimbelstern** [comment]
So the problem is just the file extension? .xml works, .grmt does not?

**Comment by serpico** [comment]
> So the problem is just the file extension? .xml works, .grmt does not?

That's what I noticed yes

**Comment by Zimbelstern** [comment]
Unfortunately, I don't have much time at the moment for Tournant. I will log my progress here.

Android 13 resolves the mime types the following way:
`android.content.ContentResolver.getType`

```
.grmt -> application/octet-stream
.json -> application/json
.xml -> text/xml
.zip -> application/zip
```
Android 5 which is the lowest Tournant supports:
```
.grmt -> application/octet-stream
.json -> application/octet-stream
.xml -> text/xml
.zip  -> application/zip
```
So the problem is that there is no way I can differentiate between `grmt` and `json` before reading the file.

This comes from the fact that earlier Android versions apparently don't support the `json` mime type and `grmt` isn't an official file extension at all. And I can not get the information from the filename because this may be obscured by the file provider. Not sure yet about the best solution.

**Comment by serpico** [comment]
Thanks for the progress report, if ultimately it's not possible to deal technically with the issue, the section about `.grmt` files in the readme could be amended to invite users to change the extension before trying to import, to work around the problem.
