### ISSUE TITLE
Yield serving error 

### ISSUE THREAD

**Issue by pled** [zimbelstern/Tournant#2]
Hi, running now 1.1.1 version. 
For some recipes, modifying the yield serving with "+" and "-" button does not work, it may lead app to crash as well.
See recipes file I provided at bug #1 , from my observations : 
- Recipe "Ajitsuke Tamago" : recipe has a quantity like "6-8" eggs (œufs), which means number of eggs is between 6 and 8... Using "+" and "-" button does not work, recipe is closed, reopen recipe, retry : app may crash.
- Recipe "Adalu" : recipe has a quantity of "1/2" onion (oignon) : this seems to be wrong with the yield serving buttons. Same behavior as above.

**Comment by zimbelstern** [comment]
It's very clear to me why this happens. One problem of Gourmand's XML export format is that there is no schema definition. Therefore, it's difficult to reverse-engineer all potential formats of an element's content (like the ingredient amount). That is why your examples are important.

It is probably a better idea to use Gourmand's internal SQL database format than the XML export files and I am going to implement this in a later version of the app. Until then, this bug will be fixed with kind of a workaround.
